# Generated by Django 2.2.16 on 2022-01-29 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220129_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiting',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raitings', to='posts.Post'),
        ),
    ]
