# Generated by Django 2.2.16 on 2022-02-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_setrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setrating',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='setrating',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
